name: Pipeline Tienda Perritos (Build & Push a ECR)

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1 # Cambia esto si tu AWS está en otra región (ej. us-east-2)
  ECR_BACKEND: tienda-backend
  ECR_FRONTEND: tienda-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y subir imagen del Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_BACKEND:latest .
          docker push $ECR_REGISTRY/$ECR_BACKEND:latest

      - name: Construir y subir imagen del Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd frontend
          docker build -t $ECR_REGISTRY/$ECR_FRONTEND:latest .
          docker push $ECR_REGISTRY/$ECR_FRONTEND:latest